# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Conserving TIFFs
email: nickkrabbenhoeft@nypl.org
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://nkrabben.github.io/tifftime" # the base hostname & protocol for your site
twitter_username: nkrabben
github_username:  nkrabben

# Build settings
markdown: kramdown
